### ISSUE TITLE
Dialog, validate before accept

### ISSUE THREAD

**Issue by fjfeijoo** [Ullfis/aurelia-mdc-bridge#13]
Is there any way to validate a form in a Dialog before is closed after clicking accept?

Thanks!

**Comment by Ullfis** [comment]
Hmmm. It’s not possible out of the box..

The [foundation](https://github.com/material-components/material-components-web/blob/master/packages/mdc-dialog/foundation.js) bind the click event [here](https://github.com/material-components/material-components-web/blob/master/packages/mdc-dialog/foundation.js#L88) and end up running [this](https://github.com/material-components/material-components-web/blob/master/packages/mdc-dialog/foundation.js#L110) function:

```javascript
  accept(shouldNotify) {
    if (shouldNotify) {
      this.adapter_.notifyAccept();
    }

    this.close();
  }
```


&lt;scratching-head&gt;

Instead of register a custom accept/cancel function and use foundation registerSurfaceInteractionHandler to handle this stuff, we could deactivate accept button until form is valid. In that case I guess it could be an attribute bound to a true/false variable.

&lt;/scratching-head&gt;

**Comment by fjfeijoo** [comment]
Yes, I don't see a clean solution using the mwc directly.

I ended up using the [aurelia-dialog](https://github.com/aurelia/dialog) plugin with a view loading the plain html directly on it.

It's working quite well for now.

**Comment by Ullfis** [comment]
I am glad you made it work :smile: 

I see the [design guideline](https://material.io/guidelines/components/dialogs.html#dialogs-specs) have one example where they disable the accept button until a choice is made. I will add an attribute so the button can be disabled.

**Comment by Ullfis** [comment]
Example added: https://ullfis.github.io/aurelia-mdc-bridge/#/components/dialogs

**Comment by fjfeijoo** [comment]
Thanks for this, it's other option to consider.

In my case on accept I want to send a request to an API, and depending on the result, the dialog closes or not.

What about something like this?

  <mdc-dialog header="Dialog header" view-model.ref="dialog">

    <p>Dialog content</p>

    <mdc-dialog-footer>
      <mdc-dialog-button cancel="true">Cancel</mdc-dialog-button>
      <mdc-dialog-button accept="false" click.trigger="myAccept($event)">Accept</mdc-dialog-button>
    </mdc-dialog-footer>
  </mdc-dialog>

Then in the model:

    myAccept(event) {
        event.stopPropagation();

        this.api.sendRequest('url')
        .then(()=> {
            // All good, accept the dialog
            this.dialog.accept();
        })
        .catch(error => this.showErrorOnDialog(error));
    }

**Comment by Ullfis** [comment]
I found something we could work on:

[Bridge dialog source](https://github.com/Ullfis/aurelia-mdc-bridge/blob/master/src/bridge/dialog/dialog.ts#L53):

```typescript

private attached() {
  this.scrollableChanged(this.scrollable);
  this.mdcElement = new MDCDialog(this.diagElement);
  ...
  // replace foundation accept function
  this.mdcElement.foundation_.accept = this.onAccept.bind(this);
  ...
```

and

```typescript
private onAccept(shouldNotify) {
  this.log.debug('Weeeee!!');
  if (shouldNotify) {
    this.mdcElement.foundation_.adapter_.notifyAccept();
  }

  this.mdcElement.foundation_.close();
}
```

Here we could control the accept flow :smile:

**Comment by Ullfis** [comment]
One option is to make the foundation public:

```javascript
this.dialog.foundation.accept = this.onAccept.bind(this);
```

**Comment by fjfeijoo** [comment]
That's great!

**Comment by Ullfis** [comment]
Custom Accept Function example added :smile:
